@echo off
echo Starting Voice Shopping Assistant...
echo.
echo 1. Starting local server on port 3001...
start "Voice Server" cmd /k "npm run server"
echo.
echo 2. Waiting 3 seconds for server to start...
timeout /t 3 /nobreak > nul
echo.
echo 3. Starting frontend on port 5173...
start "Voice Frontend" cmd /k "npm run dev"
echo.
echo Both services are starting...
echo - Server: http://localhost:3001
echo - Frontend: http://localhost:5173
echo.
echo Press any key to close this window...
pause > nul
